<a href="https://colab.research.google.com/github/lizadeka/GoogleCollab_files/blob/main/Resources/Blank_SQL_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [16]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

Connecting and switching to connection 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [17]:
%%sql

select *
from information_schema.columns
where table_name = 'customer'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

24 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
2,contoso_100k,public,customer,startdt,3,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
3,contoso_100k,public,customer,enddt,4,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
4,contoso_100k,public,customer,birthday,18,None,YES,date,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
5,contoso_100k,public,customer,age,19,None,YES,integer,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
6,contoso_100k,public,customer,latitude,23,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
7,contoso_100k,public,customer,longitude,24,None,YES,double precision,NaN,NaN,...,NO,None,None,None,None,None,NO,NEVER,None,YES
8,contoso_100k,public,customer,middleinitial,9,None,YES,character varying,5.00,20.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
9,contoso_100k,public,customer,surname,10,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
10,contoso_100k,public,customer,streetaddress,11,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
11,contoso_100k,public,customer,city,12,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
12,contoso_100k,public,customer,state,13,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
13,contoso_100k,public,customer,statefull,14,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
14,contoso_100k,public,customer,zipcode,15,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
15,contoso_100k,public,customer,country,16,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
16,contoso_100k,public,customer,countryfull,17,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
17,contoso_100k,public,customer,company,21,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
18,contoso_100k,public,customer,vehicle,22,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
19,contoso_100k,public,customer,occupation,20,None,YES,character varying,100.00,400.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
20,contoso_100k,public,customer,continent,5,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
21,contoso_100k,public,customer,gender,6,None,YES,character varying,10.00,40.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
22,contoso_100k,public,customer,title,7,None,YES,character varying,20.00,80.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES
23,contoso_100k,public,customer,givenname,8,None,YES,character varying,50.00,200.00,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [18]:
%%sql

select orderdate,
  quantity * netprice * exchangerate as net_revenue
from sales
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2015-01-01        63.49
1  2015-01-01       423.28
2  2015-01-01       108.75
3  2015-01-01      1146.75
4  2015-01-01       950.25
5  2015-01-01      1302.91
6  2015-01-01        58.73
7  2015-01-01       224.98
8  2015-01-01       263.11
9  2015-01-01       578.52

In [19]:
# recent sales >= 2020

%%sql

select orderdate,
  quantity * netprice * exchangerate as net_revenue
from sales
where
  orderdate >= '2020-01-01'
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

    orderdate  net_revenue
0  2020-01-01        99.47
1  2020-01-01       139.97
2  2020-01-01       669.39
3  2020-01-01      4090.60
4  2020-01-01       237.15
5  2020-01-01      1507.16
6  2020-01-01       189.35
7  2020-01-01       539.90
8  2020-01-01      5590.00
9  2020-01-01      3580.00

In [20]:
%%sql

select s.orderdate,
  quantity * netprice * exchangerate as net_revenue,
  c.givenname,
  c.surname,
  c.countryfull,
  c.continent,
  p.productkey,
  p.productname,
  p.categoryname,
  p.subcategoryname,
  case when quantity * netprice * exchangerate > 1000 then 'HIGH' else 'LOW' end as high_low
from sales s
left join customer c on c.customerkey = s.customerkey
left join product p on p.productkey = s.productkey
where
  orderdate >= '2020-01-01'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

124451 rows affected.

,orderdate,net_revenue,givenname,surname,countryfull,continent,productkey,productname,categoryname,subcategoryname,high_low
0,2020-01-01,3075.80,David,Stone,United States,North America,1051,"A. Datum SLR Camera 35"" M358 Silver",Cameras and camcorders,Digital SLR Cameras,HIGH
1,2020-01-01,444.34,David,Stone,United States,North America,1709,MGS Gears of War M170,Games and Toys,Download Games,LOW
2,2020-01-01,1187.73,David,Stone,United States,North America,457,WWI Desktop PC1.60 E1600 White,Computers,Desktops,HIGH
3,2020-01-01,36.78,David,Stone,United States,North America,1385,Contoso Multi-line phones M30 Grey,Cell phones,Home & Office Phones,LOW
4,2020-01-01,4.45,David,Stone,United States,North America,1665,MGS Hand Games for 12-16 boys E600 Yellow,Games and Toys,Boxed Games,LOW
...,...,...,...,...,...,...,...,...,...,...,...
124446,2024-04-20,14.35,Guus,Doodeman,Netherlands,Europe,849,Contoso Ultraportable Neoprene Sleeve E30 Green,Computers,Computers Accessories,LOW
124447,2024-04-20,261.32,Guus,Doodeman,Netherlands,Europe,1651,Contoso DVD 9-Inch Player Portable M300 Silver,"Music, Movies and Audio Books",Movie DVD,LOW
124448,2024-04-20,147.78,Michael,Wilson,Canada,North America,1575,SV DVD Player M140 Gold,"Music, Movies and Audio Books",Movie DVD,LOW
124449,2024-04-20,2019.62,Michael,Wilson,Canada,North America,415,Proseware Laptop8.9 E089 White,Computers,Laptops,HIGH
124450,2024-04-20,56.83,Michael,Wilson,Canada,North America,1693,SV Hand Games men M30 Black,Games and Toys,Boxed Games,LOW

In [21]:
# pivot with case

%%sql

select orderdate,
  count(distinct customerkey) as total_cutomers
from sales
where
  orderdate between '2023-01-01' and '2023-12-31'
group by
  orderdate
order by
  orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_cutomers
0    2023-01-01              12
1    2023-01-02              49
2    2023-01-03              64
3    2023-01-04              78
4    2023-01-05              87
..          ...             ...
359  2023-12-27              73
360  2023-12-28              75
361  2023-12-29              55
362  2023-12-30              91
363  2023-12-31               9

[364 rows x 2 columns]

In [22]:
# from matplotlib import pyplot as plt
# import seaborn as sns
# def _plot_series(series, series_name, series_index=0):
#   palette = list(sns.palettes.mpl_palette('Dark2'))
#   xs = series['orderdate']
#   ys = series['total_cutomers']

#   plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

# fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
# df_sorted = _df_1.sort_values('orderdate', ascending=True)
# _plot_series(df_sorted, '')
# sns.despine(fig=fig, ax=ax)
# plt.xlabel('orderdate')
# _ = plt.ylabel('total_cutomers')

In [23]:

%%sql

select distinct
    continent
  from
    customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0         Europe
1  North America
2      Australia

In [24]:
# pivot with count()-daily customers by region


%%sql

select s.orderdate,
  # count(distinct s.customerkey) as total_cutomers,
  count(distinct case when c.continent = 'Australia' then s.customerkey else null end) as au_customers,
  count(distinct case when c.continent = 'Europe' then s.customerkey else null end) as eu_customers,
  count(distinct case when c.continent = 'North America' then s.customerkey else null end) as na_customers
from sales s
left join customer c on c.customerkey = s.customerkey
where
  s.orderdate between '2023-01-01' and '2023-12-31'
group by
  s.orderdate
order by
  s.orderdate

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  au_customers  eu_customers  na_customers
0    2023-01-01             1             6             5
1    2023-01-02             3            15            31
2    2023-01-03             3            17            44
3    2023-01-04             4            28            46
4    2023-01-05             8            22            57
..          ...           ...           ...           ...
359  2023-12-27             6            26            41
360  2023-12-28             7            24            44
361  2023-12-29             4            19            32
362  2023-12-30            16            25            50
363  2023-12-31             0             1             8

[364 rows x 4 columns]

In [25]:
# pivot with sum()-daily customers by region

%%sql

select p.categoryname,
  # sum(s.quantity * s.netprice * s.exchangerate) as net_revenue,
  sum(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as total_net_revenue_2022,
  sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as total_net_revenue_2023
from sales s
left join product p on p.productkey = s.productkey
group by
  p.categoryname
order by
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_net_revenue_2022,total_net_revenue_2023
0,Audio,766938.21,688690.18
1,Cameras and camcorders,2382532.56,1983546.29
2,Cell phones,8119665.07,6002147.63
3,Computers,17862213.49,11650867.21
4,Games and Toys,316127.30,270374.96
5,Home Appliances,6612446.68,5919992.87
6,"Music, Movies and Audio Books",2989297.28,2180768.13
7,TV and Video,5815336.61,4412178.23

In [26]:
# Statistical Aggregations

%%sql

select p.categoryname,
  # sum(s.quantity * s.netprice * s.exchangerate) as net_revenue,
  sum(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as total_net_revenue_2022,
  sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as total_net_revenue_2023
from sales s
left join product p on p.productkey = s.productkey
group by
  p.categoryname
order by
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,total_net_revenue_2022,total_net_revenue_2023
0,Audio,766938.21,688690.18
1,Cameras and camcorders,2382532.56,1983546.29
2,Cell phones,8119665.07,6002147.63
3,Computers,17862213.49,11650867.21
4,Games and Toys,316127.30,270374.96
5,Home Appliances,6612446.68,5919992.87
6,"Music, Movies and Audio Books",2989297.28,2180768.13
7,TV and Video,5815336.61,4412178.23

In [27]:
# Statistical Aggregation

%%sql

select p.categoryname,
  # sum(s.quantity * s.netprice * s.exchangerate) as net_revenue,
  AVG(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as avg_net_revenue_2022,
  AVG(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as avg_net_revenue_2023,
  MIN(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as min_net_revenue_2022,
  MIN(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as min_net_revenue_2023,
  MAX(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as max_net_revenue_2022,
  MAX(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end) as max_net_revenue_2023
from sales s
left join product p on p.productkey = s.productkey
group by
  p.categoryname
order by
  p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_revenue_2022,avg_net_revenue_2023,min_net_revenue_2022,min_net_revenue_2023,max_net_revenue_2022,max_net_revenue_2023
0,Audio,50.18,45.06,0.00,0.00,3473.36,2730.87
1,Cameras and camcorders,176.85,147.23,0.00,0.00,15008.39,13572.00
2,Cell phones,194.66,143.89,0.00,0.00,7692.37,8912.22
3,Computers,384.13,250.55,0.00,0.00,38082.66,27611.60
4,Games and Toys,15.60,13.34,0.00,0.00,5202.01,3357.30
5,Home Appliances,390.05,349.20,0.00,0.00,31654.55,32915.59
6,"Music, Movies and Audio Books",93.37,68.11,0.00,0.00,5415.19,3804.91
7,TV and Video,425.35,322.72,0.00,0.00,30259.41,27503.12